name: Bug Report
description: File a bug report
title: '[BUG] '
labels: ['bug']
assignees:
  - Sayshal
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with the module. Please fill out all the fields to the best of your ability.
  - type: checkboxes
    id: troubleshooter
    attributes:
      label: Spell Book Troubleshooter
      description: Recreate the issue being reported in Spell Book, and without closing the application, open the troubleshooter from the Settings menu. Download the troubleshooter file and attach it below.
      options:
        - label: I understand that I will not recieve support until a troubleshooter file has been uploaded.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of the package?
      placeholder: '1.0.0'
    validations:
      required: true
  - type: input
    id: core-version
    attributes:
      label: Foundry Version
      description: What version of foundry?
      placeholder: '12.331'
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: D&D Version
      description: What version of the system?
      placeholder: '5.1.2'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
