name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths: ['docs/**']

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: joeizzard/action-wiki-sync@master
        with:
          username: ${{ github.actor }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_source_path: 'docs/'
          wiki_target_path: '.'
