name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths: ['docs/**']

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: joeizzard/action-wiki-sync@master
        with:
          username: ${{ github.repository_owner }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: docs
          commit_username: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: 'Auto-sync documentation from docs folder'
