name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths: ['docs/**']

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs').promises;
            const path = require('path');

            async function syncDocsToWiki() {
              const docsDir = './docs';
              const files = await fs.readdir(docsDir, { withFileTypes: true });

              for (const file of files) {
                if (file.isFile() && file.name.endsWith('.md')) {
                  const content = await fs.readFile(path.join(docsDir, file.name), 'utf8');
                  const pageName = file.name.replace('.md', '');

                  try {
                    // Try to update existing page
                    await github.rest.gists.createComment({
                      owner: context.repo.owner,
                      repo: `${context.repo.repo}.wiki`,
                      path: `${pageName}.md`,
                      message: `Auto-sync from docs/${file.name}`,
                      content: content
                    });
                  } catch (error) {
                    console.log(`Creating new wiki page: ${pageName}`);
                    // Create new page logic here
                  }
                }
              }
            }

            await syncDocsToWiki();
